# Generated by Django 5.1.3 on 2024-11-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_address_event_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(max_length=500),
        ),
    ]
