# Generated by Django 5.1.3 on 2024-11-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_address_alter_event_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_phone_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_phone_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free_to_visit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
