# Generated by Django 5.1.3 on 2024-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
