# Generated by Django 5.1.3 on 2024-12-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_booking_url_alter_event_contact_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
