services:
    nginx:
        image: nginx:latest
        ports:
            - 84:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d

    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - 20080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: c21716601@tudublin.ie
            PGADMIN_DEFAULT_PASSWORD: mypassword
        depends_on:
            - postgis
            - nginx

    postgis:
        image: kartoza/postgis:latest
        ports:
            - 25432:5432
        environment:
            POSTGRES_DB: gis
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker

    awm_django_app:
        image: geodjango_tutorial_image
        ports:
            - 8001:8001
        command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
        volumes:
            - .:/app
        environment:
            GDAL_DATA: /opt/conda/envs/awm-env/share/gdal
            PROJ_LIB: /opt/conda/envs/awm-env/share/proj
        depends_on:
            - postgis
            - nginx
            - pgadmin4
