services:
    nginx:
        image: nginx:latest
        ports:
            - 84:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - awm_django_app  # Only nginx depends on awm_django_app

    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - 20080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: emilroy100@gmail.com
            PGADMIN_DEFAULT_PASSWORD: emilroy100
        depends_on:
            - postgis

    postgis:
        image: kartoza/postgis:latest
        ports:
            - 25432:5432
        environment:
            POSTGRES_DB: gis
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        volumes:
            - postgis_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data

    awm_django_app:
        build: .
        ports:
            - 8001:8001
        entrypoint: ["/app/docker-entrypoint.sh"]
        command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
        volumes:
            - .:/app
        environment:
            GDAL_DATA: /opt/conda/envs/awm-env/share/gdal
            PROJ_LIB: /opt/conda/envs/awm-env/share/proj
            POSTGRES_HOST: postgis
            POSTGRES_PORT: 5432
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        depends_on:
            - postgis
            - pgadmin4

volumes:
    postgis_data:  # Define the persistent volume for PostgreSQL
